nickdowell:
  amsynth:
    general:
      bank_select:
        { cc: 0, description: "Change sound bank", init: 0, min: 0, max: 127 }
      preset_select: "program_change"

      filter_velocity_sens:
        {
          cc: 20,
          description: "Filter Velocity Sensitivity",
          init: 127,
          min: 0,
          max: 127,
        }
      amp_velocity_sens:
        {
          cc: 21,
          description: "Amp Velocity Sensitivity",
          init: 127,
          min: 0,
          max: 127,
        }
    oscillators:
      osc1_waveform:
        {
          cc: 103,
          description: "Oscillator 1 Waveform",
          init: 64,
          min: 0,
          max: 127,
        }
      osc1_shape:
        {
          cc: 104,
          description: "Oscillator 1 Shape",
          init: 64,
          min: 0,
          max: 127,
        }
      osc2_waveform:
        {
          cc: 105,
          description: "Oscillator 2 Waveform",
          init: 64,
          min: 0,
          max: 127,
        }
      osc2_shape:
        {
          cc: 106,
          description: "Oscillator 2 Shape",
          init: 64,
          min: 0,
          max: 127,
        }
      osc2_oct:
        {
          cc: 108,
          description: "Oscillator 2 Range",
          init: 64,
          min: 0,
          max: 127,
        }
      osc2_semitone:
        {
          cc: 109,
          description: "Oscillator 2 Pitch",
          init: 64,
          min: 0,
          max: 127,
        }
      osc2_detune:
        {
          cc: 110,
          description: "Oscillator 2 Detune",
          init: 64,
          min: 0,
          max: 127,
        }
      sync_oscillators:
        { cc: 107, description: "Sync Oscillators", init: 64, min: 0, max: 127 }
      mix:
        { cc: 111, description: "Oscillator Mix", init: 64, min: 0, max: 127 }
      ring_mod:
        { cc: 112, description: "Ring Modulator", init: 64, min: 0, max: 127 }
    amp:
      volume:
        { cc: 7, description: "Master Volume", init: 64, min: 0, max: 127 }
      panning:
        { cc: 10, description: "Panning sound", init: 64, min: 0, max: 127 }
      drive:
        { cc: 15, description: "Distortion Crunch", init: 0, min: 0, max: 127 }
      attack: { cc: 57, description: "Amp Attack", init: 64, min: 0, max: 127 }
      decay: { cc: 58, description: "Amp Decay", init: 64, min: 0, max: 127 }
      sustain:
        { cc: 59, description: "Amp Sustain", init: 64, min: 0, max: 127 }
      release:
        { cc: 60, description: "Amp Release", init: 64, min: 0, max: 127 }
    filter:
      type: { cc: 47, description: "Filter Type", init: 64, min: 0, max: 127 }
      slope: { cc: 48, description: "Filter Slope", init: 0, min: 0, max: 127 }
      cutoff:
        { cc: 50, description: "Filter Cutoff", init: 0, min: 0, max: 127 }
      resonance:
        { cc: 49, description: "Filter Resonnance", init: 0, min: 0, max: 127 }
      key_track:
        {
          cc: 51,
          description: "Filter Keyboard Track",
          init: 127,
          min: 0,
          max: 127,
        }
      env_amount:
        {
          cc: 52,
          description: "Filter Env Amount",
          init: 127,
          min: 0,
          max: 127,
        }
      attack:
        { cc: 53, description: "Filter Env Attack", init: 0, min: 0, max: 127 }
      decay:
        { cc: 54, description: "Filter Env Decay", init: 64, min: 0, max: 127 }
      sustain:
        {
          cc: 55,
          description: "Filter Env Sustain",
          init: 64,
          min: 0,
          max: 127,
        }
      release:
        {
          cc: 56,
          description: "Filter Env Release",
          init: 64,
          min: 0,
          max: 127,
        }
    lfo:
      waveform:
        { cc: 118, description: "LFO Waveform", init: 64, min: 0, max: 127 }
      speed: { cc: 119, description: "LFO Speed", init: 64, min: 0, max: 127 }
      target: { cc: 117, description: "LFO Target", init: 64, min: 0, max: 127 }
      freq_mod_amount:
        { cc: 1, description: "LFO Freq Mod Amount", init: 0, min: 0, max: 127 }
      filter_mod_amount:
        {
          cc: 116,
          description: "Filter Mod Amount",
          init: 64,
          min: 0,
          max: 127,
        }
      amp_mod_amount:
        { cc: 115, description: "Amp Mod Amount", init: 64, min: 0, max: 127 }
    reverb:
      amount: { cc: 91, description: "Reverb Wet", init: 64, min: 0, max: 127 }
      size:
        { cc: 92, description: "Reverb Room Size", init: 64, min: 0, max: 127 }
      stereo:
        { cc: 93, description: "Reverb Width", init: 64, min: 0, max: 127 }
      damping:
        { cc: 94, description: "Reverb Damp", init: 64, min: 0, max: 127 }
    keys:
      notes: "keys_or_pads"
      pitchwheel: "pitchwheel"
      portamento:
        { cc: 22, description: "Portamento Time", init: 0, min: 0, max: 127 }
      portamento_mode:
        { cc: 23, description: "Portamento Mode", init: 0, min: 0, max: 127 }
      keyboard_mode:
        { cc: 24, description: "Keyboard Mode", init: 0, min: 0, max: 127 }
